### ISSUE TITLE
"use" / includes not available

### ISSUE THREAD

**Issue by eckhardEhm** [GillesBouissac/agentscad#1]
hey and thanks for sharing your awesome library.

It is not possible to use it though without having your specific local directory setup and other files referenced.

For example in this file:
agentscad/snap-joint.scad 

There are several "use" calls to files that are not a git submodule and not part of this repository:
```
use <scad-utils/lists.scad>
use <scad-utils/transformations.scad>
use <agentscad/extensions.scad>
use <agentscad/printing.scad>
use <list-comprehension-dems/sweep.scad>
```
Cloning your scad-utils and moving some files to ./agentscad does help.
But the "sweep.scad" is calling in more files that I dont know where to find.

Could you provide the whole thing?
So that you can just clone / download in a new directory and it will run in openscad.

**Comment by GillesBouissac** [comment]
Hi,

To use this lib you just need some prerequisite manipulations described [in this page](https://github.com/GillesBouissac/agentscad/wiki/Prerequisites).

Hope this will fix your issues.
