### ISSUE TITLE
Bolts have undersized external thread diameter

### ISSUE THREAD

**Issue by yrk-lab** [GillesBouissac/agentscad#2]
Test case:
```
use <agentscad/mx-screw.scad>
use <agentscad/mx-thread.scad>

$fn=36;

difference() {
  union(){
    mxBoltHexagonalThreaded(M5());
    mxNutHexagonalThreaded(M5());
  }
  translate([0, 0, -5]) cube([10, 10, 20]); // x-section
}
```
![mx-thread-sample-bug](https://user-images.githubusercontent.com/11537279/103174492-8aed5c00-485a-11eb-9977-d346240eb2de.png)

I verified it's bolts by 3D-printing both bolt and nut in M3 size and trying to fit those with standard steel ones. Nuts are fine, bolts are not.

**Comment by GillesBouissac** [comment]
Hello,
My designs are all made to be 3D printable. The main consequence is that everytime i need parts to be able to slide over each other i use the API gap() from printing.scad.
This gap is by default 0.2mm, this is a value that works very well with my printer (mk3s). In the case of threads, to take into account thread angles, the bolt threads diameters are reduced by `3/4*gap()` from perfect profile and bolt threads diameters are reduced by `1*gap()` from perfect profile .
The result of the gap between external and internal threads is then `3/4*0.2 + 0.2 = 0.35mm`. This is very close to the thread pitch of a M5 screw `0.5mm`. Given that this gap is set on both sides of the thread this gives `0.7mm` gap if your printer is too much precise, this explain why you find this not working. You need a lesser gap between threads.

The good thing is that this is easy to change gap value, I defined a special variable `$gap` for this. This variable defaults to 0.2mm and you can set another value to see the changes.

This works exactly like $fn special variable:
```
$fn=36;
$gap=0.1; // =0 for no gap between external and internal threads

difference() {
...
```
or 
```
$fn=36;

difference() {
union(){
    mxBoltHexagonalThreaded(M5(), $gap=0.1); // Change gap only on bolt
    mxNutHexagonalThreaded(M5());
...
```
