### ISSUE TITLE
minor bug in lib-screw.scad

### ISSUE THREAD

**Issue by Herwig1** [GillesBouissac/agentscad#4]
When calling libNutHexagonal( p, false, false) or libBoltHexagonal( p, false, false) nut or bolt-head disappear. 
My fix is:
module libBevelShape( l, d, a=BEVEL_HEXA_A, b=true, t=true ) {
    h  = (d/2)*tan(a);
    r  = (l+h)/tan(a);
    intersection() {
        if ( t ) {
            translate([0,0,-l/2])
            cylinder( r1=r, r2=0, h=(l+h) );
        }
        if ( b ) {
            translate([0,0,-h-l/2])
            cylinder( r1=0, r2=r, h=(l+h) );
        } 
      //new 
       if ( (!t) && (!b) ) {               
            cylinder( r1=r, r2=r, h=l, center=true );
       }      
    }
}

**Comment by GillesBouissac** [comment]
Thanks for this, I fixed it in order to avoid computations when not needed.
