### ISSUE TITLE
HEIGHT parameter seems to have no effect beyond 20/30

### ISSUE THREAD

**Issue by emeyedeejay** [GillesBouissac/agentscad#5]
Hi! Love this item - so useful!

Seems that the HEIGHT parameter stops having effect beyond 20/30. Any reason why?
![220528205515-Sharex screenshot](https://user-images.githubusercontent.com/8543879/170839271-aa959886-8887-45aa-8d47-57262b8c8809.png)
![220528205557-Sharex screenshot](https://user-images.githubusercontent.com/8543879/170839279-c411b2e1-18e3-4d59-acf8-ebb0331606dd.png)
![220528205618-Sharex screenshot](https://user-images.githubusercontent.com/8543879/170839283-6f24edbe-42ce-4646-82ee-21834ca24456.png)
![220528205646-Sharex screenshot](https://user-images.githubusercontent.com/8543879/170839287-33eae585-ae68-49ca-adfb-bf67db3f9445.png)
![220528205716-Sharex screenshot](https://user-images.githubusercontent.com/8543879/170839290-9022c3b8-c566-44f3-95dc-5f6c6c49fc0b.png)

The cap seems to grow but not the knob.

Thanks for looking!
Cheers
Mike

**Comment by GillesBouissac** [comment]
Thank you for this detailed issue, hope this commit will fix it for you. I also added a height limit for the cap, it don't need to be that long to close the hole. And if this don't suits you you can also force cap height with new parameter `cap_height`.

**Comment by emeyedeejay** [comment]
Brilliant - thank you ... I need some particularly long knobs for a tightener where there is very very little finger space so a 50mm knob is what I am after. I'll check out fix 5 shortly 👍

**Comment by emeyedeejay** [comment]
What do I do with that test-mx-knob.scad file? Does that go into the agent library folder?

**Comment by emeyedeejay** [comment]
Ok fathomed it out ... It's AWESOME! 😁

 
![image](https://user-images.githubusercontent.com/8543879/173362724-1687224d-fb54-4df6-b1c7-cf2eb1a51ff9.png)
