### ISSUE TITLE
How come hirthJointRectangular parts have slop?

### ISSUE THREAD

**Issue by drf5n** [GillesBouissac/agentscad#6]
<img width="673" alt="image" src="https://github.com/GillesBouissac/agentscad/assets/2236516/858cc033-6141-4347-8e2f-e1a7d6064046">
This is a screenshot of https://github.com/GillesBouissac/agentscad/blob/master/test/test-hirth-joint.scad

...

Ah -- I see it is from hirthJointProfileRectangle()

https://github.com/GillesBouissac/agentscad/blob/d146a7e2b9cdc87eaee0589c107d81b24fb9ce29/hirth-joint.scad#L118-L125

and

https://github.com/GillesBouissac/agentscad/blob/d146a7e2b9cdc87eaee0589c107d81b24fb9ce29/printing.scad#L27-L28

as explained here:

https://github.com/GillesBouissac/agentscad/issues/2#issuecomment-753160869

...so setting `$gap` would control the slop: 

```
use <agentscad/hirth-joint.scad> // https://github.com/GillesBouissac/agentscad

MARGIN = 0.2;

$gap = 0.0;

module testHirthPair(){     
    difference() {
        union() {
            hirthJointRectangle( 5, 11, 1, 1, 1, shift=0.5 );
            translate( [0,0,3+0.01] )
            rotate([0,180,0])
                hirthJointRectangle( 5, 11, 1, 1, 1, shift=0.5 );
        }
        cylinder(r=2.5,h=10, center=true);
    }
}

testHirthPair();
```

**Comment by drf5n** [comment]
Here's another test script

```
use <agentscad/hirth-joint.scad> // https://github.com/GillesBouissac/agentscad

// per https://github.com/GillesBouissac/agentscad/issues/6


// type
type = "triangle"; // ["triangle","rectangle","sinus"]
// Outer radius 
RADIUS   = 10;
// number of teeth
TOOTH    = 21;
// tooth height
HEIGHT   = 1.2;
// base under teeth
SHOULDER = 1;
// base under shoulder
INLAY    = 2;
// through hole
through_hole = 2.5;
// Inner tooth radius
RMIN = 2;

// gap between mating parts
$gap = 0.2;

// ??
xINTER    = 10;
xMARGIN = 0.2;

// Show mating assembly
ASSEMBLY = true;

module myHirth(type,sh){
   if(type == "triangle"){
    hirthJointTriangle( RADIUS, TOOTH, HEIGHT, SHOULDER, INLAY, shift=sh, rmin = RMIN );      
   } else if (type == "sinus") {
    hirthJointSinus( RADIUS, TOOTH, HEIGHT, SHOULDER, INLAY, sh, rmin = RMIN );      
   } else if (type == "rectangle") {
           hirthJointRectangle( RADIUS, TOOTH, HEIGHT, SHOULDER, INLAY, shift=sh, rmin = RMIN );      
   } else {
       cube(HEIGHT);
   }
}

module testHirthPair(){     
    difference() {
        union() {
            myHirth(type,0);
           %  if(ASSEMBLY)
               translate( [0,0,HEIGHT+2*SHOULDER+$gap+0.01] )
               rotate([0,180,180])
               myHirth(type,0.5);
           }
        cylinder(r=through_hole,h=2*(HEIGHT+SHOULDER+INLAY+5), center=true);
    }
}
    
    
testHirthPair();
```
It does the assembly with a vertical gap:

<img width="435" alt="image" src="https://github.com/GillesBouissac/agentscad/assets/2236516/ea00612b-0e69-468d-90d4-f430444536d5">

and switches between triangle and sinus:
<img width="452" alt="image" src="https://github.com/GillesBouissac/agentscad/assets/2236516/db50027d-a074-45fa-b28f-cfbd09bc8f7d">

<img width="467" alt="image" src="https://github.com/GillesBouissac/agentscad/assets/2236516/0df5b225-86b3-4dcf-91ad-2677d871d9c6">

**Comment by GillesBouissac** [comment]
Sorry for the no response i am struggling with 2FA.
Well done you found the solution :)
