### ISSUE TITLE
Screws not rendering in OpenSCAD 2021

### ISSUE THREAD

**Issue by LIII-XXII** [GillesBouissac/agentscad#8]
The following code (from the tutorials) sometimes does not render the threaded part of the bolts. The console shows a "mesh not closed" error:

```openscad
use <agentscad/mx-screw.scad>
use <agentscad/mx-thread.scad>


// M6 bolt with 10mm thread length
$fn=50;
screw  = M6();
mxBoltHexagonalThreaded(screw,10);

translate([50, 0, 0])
  mxBoltAllenThreaded(screw,20);
```

screenshot of the preview:
![image](https://github.com/GillesBouissac/agentscad/assets/583664/f4eda6d7-1b78-40bc-921d-c504116ba1ba)

screenshot of the render:

**Comment by LIII-XXII** [comment]
after restarting openscad, the error disappeared. I wonder if somehow I had some bad data from a previous render in the cache?

will reopen if I manage to reproduce it

**Comment by GillesBouissac** [comment]
Hello, i didn't test with OpenSCAD 2021.01, try updating your version, i'm using 2024.03.03
