### ISSUE TITLE
metric screw diameter seems lower than nominal

### ISSUE THREAD

**Issue by LIII-XXII** [GillesBouissac/agentscad#9]
with the following code:

```openscad
use <agentscad/mx-screw.scad>
use <agentscad/mx-thread.scad>

$fn=50;
screw  = M3(tl=2);
translate([0, 0, -.001])
  mxBoltAllenThreaded(screw,10);
```

I am expecting to generate an M3 screw, which should have an external diameter of 3mm, but rendering shows a screw whose diameter is closer to 2*1.35mm (2.7mm):

![image](https://github.com/GillesBouissac/agentscad/assets/583664/8e73a52c-8184-4582-beeb-81b185719c28)

is this a tolerance for printing?I would like to be able to adjust it because this is in fact too small to catch threads of metal nuts.

**Comment by LIII-XXII** [comment]
here's a picture to show the result:

![image](https://github.com/GillesBouissac/agentscad/assets/583664/7ce09f2e-8d8d-4601-b01d-464a4d71191d)

from left to right: a metal M3 bolt, a 3d printed bolt, a metal M3 nut, a nut on top of a 3d printed bolt (the threads do not catch)

**Comment by GillesBouissac** [comment]
Hello,
I've defined some special variables here: https://github.com/GillesBouissac/agentscad/blob/master/printing.scad
$gap is used (default 0.2mm) to set the distance between parts that need to slide on each other.
Then you can control this by setting it globally (as you did for $fn) or in each call

```
...
$gap=0;
...
```
or
```
...
  mxBoltAllenThreaded(screw, 10, $gap=0);
...
```

**Comment by LIII-XXII** [comment]
thank you, I'll try this next time!
